import { NextRequest, NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";

const PLATFORMS = ["android", "ios", "web"];

// Called by the mobile app on first launch.
// device_id is a stable per-install identifier generated by the app.
// install_source / install_referrer carry attribution ("from where").
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { device_id, platform, app_version, install_source, install_referrer, country } = body;

    if (!device_id || typeof device_id !== "string") {
      return NextResponse.json({ error: "device_id is required" }, { status: 400 });
    }

    const supabase = createServiceClient();
    const now = new Date().toISOString();
    const id = device_id.trim();

    const { error } = await supabase.from("app_installs").insert({
      device_id:        id,
      platform:         PLATFORMS.includes(platform) ? platform : "unknown",
      app_version:      app_version?.toString().trim() || null,
      install_source:   install_source?.toString().trim() || "organic",
      install_referrer: install_referrer?.toString().trim() || null,
      country:          country?.toString().trim().toUpperCase().slice(0, 2) || null,
      first_seen:       now,
      last_seen:        now,
    });

    // 23505 = unique_violation → device already installed. Preserve first-touch
    // attribution, just record that the device is active again.
    if (error?.code === "23505") {
      await supabase.from("app_installs").update({ last_seen: now }).eq("device_id", id);
      return NextResponse.json({ ok: true, status: "already_installed" });
    }
    if (error) {
      console.error("[app/install] Supabase insert error:", error.message);
      return NextResponse.json({ error: "Failed to record install" }, { status: 500 });
    }

    return NextResponse.json({ ok: true, status: "installed" });
  } catch (err) {
    console.error("[app/install] Unexpected error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
